name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Navigate to project directory
      run: cd SupFAmof_Project_API  # Update this path if needed

    - name: Build and publish
      run: |
        dotnet publish -c Release -o out
        echo "Application published to out directory"

    - name: Build Docker image
      run: |
        docker build -t manh222/supfamof:0.0.4 .
        docker push manh222/supfamof:0.0.4

    - name: Log in to AWS Lightsail instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
        port: 22
        script: |
          sudo docker stop my-testdeploy || true
          sudo docker rm my-testdeploy || true
          sudo docker pull manh222/supfamof:0.0.4
          sudo docker run -d --name my-testdeploy -p 7049:80 manh222/supfamof:0.0.4
