name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

     - name: Run tests
      run: |
        dotnet test
        
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t manh222/supfamof:0.0.4 .
        docker push manh222/supfamof:0.0.4

    - name: Log in to AWS Lightsail instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
        port: 22
        script: |
          sudo docker stop my-testdeploy || true
          sudo docker rm my-testdeploy || true
          sudo docker pull manh222/supfamof:0.0.4
          sudo docker compose -f /home/ubuntu/my_app/docker-compose.yml up -d


